# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_4LOzX-2il4oHnEWThbEXDodEXXd58f
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TrainYolo2419
!git clone https://github.com/WongKinYiu/yolov7.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TrainYolo2419/yolov7
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TrainYolo2419/yolov7
!pip install pycocotools

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TrainYolo2419/yolov7
!rm data/mydataset.yaml
!echo 'train:  ../data_set/train' >> data/mydataset.yaml
!echo 'val: ../data_set/train' >> data/mydataset.yaml
!echo 'nc: 7' >> data/mydataset.yaml
!echo "names: ['id', 'name', 'dob', 'sex', 'nationality', 'hometown', 'address']" >> data/mydataset.yaml

# Commented out IPython magic to ensure Python compatibility.
#Train model YOLO
# %cd /content/drive/MyDrive/TrainYolo2419/yolov7
!python train.py --batch 8 --cfg cfg/training/yolov7.yaml --epochs 100 --data data/mydataset.yaml --weights 'runs/exp24/weights/best.pt'